[package]
name = "mioplays"
version = "0.0.0"
edition = "2024"

[dependencies]
slint = {version = "1.14", no-default-features = true, features=["std", "backend-default","renderer-skia", "accessibility", "compat-1-2"]}

[build-dependencies]
slint-build = "1.14"
