[package]
name = "mioplays"
version = "0.0.0"
edition = "2024"

[dependencies]
slint = {version = "1.14", features=["renderer-skia", "accessibility"]}
smol = "2.0"

[build-dependencies]
slint-build = "1.14"
