[package]
name = "mioplays"
version = "0.0.0"
edition = "2024"

[dependencies]
image = "0.25"
jiff = "0.2"
lofty = "0.22"
oneshot = "0.1.13"
slint = {version = "1.15", features=["renderer-skia", "accessibility"]}
smol = "2.0"

[build-dependencies]
slint-build = "1.14"
